name: Build iOS App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: macos-latest  # Use the macOS runner provided by GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1  # Use a specific version that exists
        with:
          xcode-version: '14.x'
          
      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install

      - name: Build and Archive iOS App
        run: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourAppScheme -sdk iphoneos -configuration Release archive -archivePath $PWD/build/YourApp.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/YourApp.xcarchive -exportPath $PWD/build -exportOptionsPlist ExportOptions.plist

      - name: Upload .ipa to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ipa-file
          path: build/BmiCalculator.ipa
